[[GAP_pkg_float]]
arch = "aarch64"
git-tree-sha1 = "e7e4772abe858abe47469fad51c84e431df411cc"
os = "macos"

    [[GAP_pkg_float.download]]
    sha256 = "72410f746ace0c845a3b4c75fd78e95b26fe126b4f4d1c37fb06e0acf10de06a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v101.1000.1+0/GAP_pkg_float.v101.1000.1.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_float]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "51d20c0f6177e1901d938b0035f612e748e6bc08"
libc = "glibc"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "457f79c352f9d1d5a45ecf8ce73ef4be36783615fe7e6d0d0181a505ae9c89d1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v101.1000.1+0/GAP_pkg_float.v101.1000.1.aarch64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_float]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8f584ab4abc8a93b1e0a264fb7d03efa4ca2f43"
libc = "musl"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "b4462911351be6712bf79279547000d9110a9800a82c17e30d7e20fb1d0b3df9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v101.1000.1+0/GAP_pkg_float.v101.1000.1.aarch64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_float]]
arch = "aarch64"
git-tree-sha1 = "36bb43f8bc342c2f0892276b315569921dc6583b"
os = "freebsd"

    [[GAP_pkg_float.download]]
    sha256 = "0aec5edb811073966f5f2c1117711b2dc79a57989c50c8b0b9311c32b7967209"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v101.1000.1+0/GAP_pkg_float.v101.1000.1.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_float]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3a1f6f1ab85f117d5b5f1faba4ab983c3ef12b28"
libc = "glibc"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "e38b178f0dfefcf2236d43f698344720e13fa64e0443509b8ece7239614f74e6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v101.1000.1+0/GAP_pkg_float.v101.1000.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_float]]
arch = "x86_64"
git-tree-sha1 = "d9892d3470581cd28264cf87a84245981143ee65"
os = "macos"

    [[GAP_pkg_float.download]]
    sha256 = "a7fda7a4f7c2fc3a01ff349b88330cc0f2a7b5e1691a1a244f74f334db105d84"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v101.1000.1+0/GAP_pkg_float.v101.1000.1.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_float]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d7b7ef62608ec07a13285300e125c70af23a7be8"
libc = "glibc"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "cc522597644a8be58670668b2207205506646509e06dbe86158bc2c68043578e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v101.1000.1+0/GAP_pkg_float.v101.1000.1.x86_64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_float]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fec9d218dbf792315da8ef2845c185113e2d2144"
libc = "musl"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "10a72f84da12273d4c80f75c3d9d79338efa7398d1f24c8c025a42be21d554bd"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v101.1000.1+0/GAP_pkg_float.v101.1000.1.x86_64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_float]]
arch = "x86_64"
git-tree-sha1 = "d1ae6c6f401e2aa28ba9332a90e36a2ce0bd1bc6"
os = "freebsd"

    [[GAP_pkg_float.download]]
    sha256 = "9f3d70e6f9883e9232d01ccb903f4b444cc035792786dd33522385b6aaf1de2d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v101.1000.1+0/GAP_pkg_float.v101.1000.1.x86_64-unknown-freebsd.tar.gz"
