[[GAP_pkg_float]]
arch = "aarch64"
git-tree-sha1 = "43f45dbddfa9fb5d8c451928837a659d5c21759e"
os = "macos"

    [[GAP_pkg_float.download]]
    sha256 = "c934c8336d5a8979a1ad9acbdf97f3db803241848fc62e0c0b524017fa8025f9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.502+0/GAP_pkg_float.v100.0.502.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_float]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b6079e52a80baff1365277426117e732140a03eb"
libc = "glibc"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "40a6e9657aa1d9e1b90640b238a3e695a8d50f5048c236f799a54b74fd6f851d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.502+0/GAP_pkg_float.v100.0.502.aarch64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_float]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "603d8c62f544b4bd4d37c3387bf61dcaff140419"
libc = "glibc"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "d7faac5625e26072c6057c5b70a248cc8b403fb2240d52280c82ffe74af8a6d3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.502+0/GAP_pkg_float.v100.0.502.aarch64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_float]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a4659a1ed5e97700c1071d49dd4ef5efb106fa94"
libc = "musl"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "8f1f5d3bdbe97e3b23ff4e7ea8292783eaa6de4f1e051ea9ee7a4a600d1e0a4a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.502+0/GAP_pkg_float.v100.0.502.aarch64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_float]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e1ba4a0c193049ccee2f3d4a812963952f9c433"
libc = "musl"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "b3790aae3ee9d1b0317b9c278f0c961d9ab08bdd2c588dff1b01b5cad6e8d563"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.502+0/GAP_pkg_float.v100.0.502.aarch64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_float]]
arch = "aarch64"
git-tree-sha1 = "000d86dc0ea94838c029098109b7e0db5873bab3"
os = "freebsd"

    [[GAP_pkg_float.download]]
    sha256 = "52436ac8595f0d1214cd6eae0165006e5ca4f3cee817bc976791da7a78492c6c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.502+0/GAP_pkg_float.v100.0.502.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_float]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "88d76ca7258101f9867234bea8f9b9c4bb375f7e"
libc = "glibc"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "4a97820525bbd4fe6d2d033af2c5c90ea0da5f968bd8c0a1bb988842c15356bf"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.502+0/GAP_pkg_float.v100.0.502.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_float]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9d54e8a228ad5aa68c6197a43014516723d6a8e4"
libc = "glibc"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "f3cf3ff5b43aa9adacc9b4ddc51cc04e003135b282e4bb33e7cca6eb369bbc46"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.502+0/GAP_pkg_float.v100.0.502.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_float]]
arch = "x86_64"
git-tree-sha1 = "d7afaad2333797215200df097cb52db2ded07e7b"
os = "macos"

    [[GAP_pkg_float.download]]
    sha256 = "96e8e71ea2122d59706ffeac397a8ec9b98954041f0aa5a16a79446c64e4ec76"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.502+0/GAP_pkg_float.v100.0.502.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_float]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c812dc2a3a5b48cf72a1d6a4ae1d28d601848664"
libc = "glibc"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "1a26fe3cb6557eae30117567b16f4341f41d39a7e928ddefbf56a400fb30bfcd"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.502+0/GAP_pkg_float.v100.0.502.x86_64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_float]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b999e03b5663dfca977ea30be7b8dca170ddbab0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "78fd0080cfa70ad7345b9c366f7e035f491a2a93795ba1fa943bec99d3e860f0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.502+0/GAP_pkg_float.v100.0.502.x86_64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_float]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fe686b91b3852eb756c0fc016fa41e1c035a2601"
libc = "musl"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "25c104242d9c846830622650cbf4f90cd0fccad6f30de22bbc57be2e560e9020"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.502+0/GAP_pkg_float.v100.0.502.x86_64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_float]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9ad8ee059544765ed79b646487f4af762207d1fc"
libc = "musl"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "c1f94da12f8f63e2216437bba5fe56b547590594f198807517f52d8758d46922"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.502+0/GAP_pkg_float.v100.0.502.x86_64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_float]]
arch = "x86_64"
git-tree-sha1 = "14df4f3096297dd813605b20f9edcb038e7d1edd"
os = "freebsd"

    [[GAP_pkg_float.download]]
    sha256 = "1baabeb1a999465463e84cdf142a78124cc7399f1c1a7fa10f009c5053e114bb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.502+0/GAP_pkg_float.v100.0.502.x86_64-unknown-freebsd.tar.gz"
