[[GAP_pkg_float]]
arch = "aarch64"
git-tree-sha1 = "3664283d2935b271b7c5f687c9a67ae11f2cc06d"
os = "macos"

    [[GAP_pkg_float.download]]
    sha256 = "df9cf96e85b65d8161adf2df174da6854320a9cbb30d58cca5efd5aee9b6560a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.300+1/GAP_pkg_float.v100.0.300.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_float]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eeb9260a2f9d1daaede08c0a83bb8371e1ce4627"
libc = "glibc"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "98caf40fedbe50fec051e1880f0e73082e90acd467e5de8975176101b2e3a8a3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.300+1/GAP_pkg_float.v100.0.300.aarch64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_float]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f6df2ae548e7df93420ffba51ae315fc9e6f5cc5"
libc = "glibc"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "8a60f3776920e2ff11444be8fdc21c0650f01280313382fda66e2f7e7fd9544f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.300+1/GAP_pkg_float.v100.0.300.aarch64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_float]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "38088a7d196d58c9ac7f2c1ad26be42f384f450f"
libc = "musl"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "60b84c1ac99489ec18238a3b0529f5e6eb6b665b786b1a6f326f4f04e9c3fb95"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.300+1/GAP_pkg_float.v100.0.300.aarch64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_float]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "247790d0f7e25cddf371e21744fe9a8f5ae7d78d"
libc = "musl"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "7713501ad91de1260191276f50bb6e717f2b59c5c8155b205b7dee796ab4390e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.300+1/GAP_pkg_float.v100.0.300.aarch64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_float]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1262b1fa29775be88384862d3639d3bf8a60cbe8"
libc = "glibc"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "3fdbf2e7b6b23ae899f0a313bacfc149f864192c18090c8f48f989d4a8dda228"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.300+1/GAP_pkg_float.v100.0.300.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_float]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b9373942e95f01fa97b3798627b2d612d23b21ac"
libc = "glibc"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "3913037acf4f2419c8f5fd046d7206212c23d8a3d3d6cfcf466822b4c474adf5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.300+1/GAP_pkg_float.v100.0.300.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_float]]
arch = "x86_64"
git-tree-sha1 = "6e2c11ff903af71a9ee50bd51b6ec0a41fd7c035"
os = "macos"

    [[GAP_pkg_float.download]]
    sha256 = "4c515ad15a0ecaef99c6230387a0f4af928571f4e797411ea19987bf554a61a6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.300+1/GAP_pkg_float.v100.0.300.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_float]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a4afec46c2584a16fb2c13898269a5020bbe584f"
libc = "glibc"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "fed1b5271573bb2109bd2ebb52d9730095a70ee57d0b65be95002d0ca6f7cca9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.300+1/GAP_pkg_float.v100.0.300.x86_64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_float]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f36390df15ce76ce428b6436167580fd7caad3f"
libc = "glibc"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "7c447ca1b0dceaab10dc56bcc8ea4bee411a04bc42b43c723918d41d425be7ce"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.300+1/GAP_pkg_float.v100.0.300.x86_64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_float]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "975b20989dd9ef7bf740e9e24902783e5fb12b9c"
libc = "musl"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "1a0e5315a1cc3d0a977557c0c629dd0b6c2fc6328d4e701d3d51d3ec95325061"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.300+1/GAP_pkg_float.v100.0.300.x86_64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_float]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56156525d95470a864dd313584195d067190d03a"
libc = "musl"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "d662ad34799a692f191f057c71b934352ace546c5d4512d6235bd8067b56a020"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.300+1/GAP_pkg_float.v100.0.300.x86_64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_float]]
arch = "x86_64"
git-tree-sha1 = "3fc2bd5cfc7d793419474f459f14d6bf717c4b98"
os = "freebsd"

    [[GAP_pkg_float.download]]
    sha256 = "97a063094752ec5e763e948ac52613c1fc1d1fc2495a4006c61ebec193a717ca"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.300+1/GAP_pkg_float.v100.0.300.x86_64-unknown-freebsd.tar.gz"
