[[GAP_pkg_float]]
arch = "aarch64"
git-tree-sha1 = "cdf7fa4a64871691456fae84d7f4aaec09521033"
os = "macos"

    [[GAP_pkg_float.download]]
    sha256 = "f0c04ed4f1fced2fb4650b8fc655d25b4c7da64067eec348efb096bcf496046d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.500+0/GAP_pkg_float.v100.0.500.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_float]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8efd0971f9bc5d44c7ed8d5b545077c58ad99fa9"
libc = "glibc"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "74d8a275bab24e9bb36f9c27939e92021ca31abb36140a66c80144ca7c8b2335"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.500+0/GAP_pkg_float.v100.0.500.aarch64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_float]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e9ac24468fb826202add288569a551fb21a885b"
libc = "glibc"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "f9d37b50d21d4bc1837736ac3ef99540a94617c4889ac2bfe80d6ee9d0adff41"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.500+0/GAP_pkg_float.v100.0.500.aarch64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_float]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aa4faf2178f56dba5477606c273d728c513f557d"
libc = "musl"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "071ceb97c5bca7dfe2713b4c8e86c64bd15e39c53de97e06f2df7dca3ccc8f9e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.500+0/GAP_pkg_float.v100.0.500.aarch64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_float]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "57a365a1298eb61373bac4093095f904f6a3ab93"
libc = "musl"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "1896e9e4c12037b94abc1532fde272f71b715fbd2d17c96b8cd500c9c43bd7cc"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.500+0/GAP_pkg_float.v100.0.500.aarch64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_float]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3dbb1e1589a799a375a616701c8490db890bc0c1"
libc = "glibc"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "6e4864bcb9a40d06ed267f63196740ee5e661b1cf70b2031dd268a564c799e25"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.500+0/GAP_pkg_float.v100.0.500.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_float]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "127e8efce9fa6e195924f5d0baa8359e3a4beec0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "2815660468790f02a767f0bae56e8b15de0eddfec4abded4ec8c34fea07bebdb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.500+0/GAP_pkg_float.v100.0.500.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_float]]
arch = "x86_64"
git-tree-sha1 = "2e0be61f2ae11fecfaf6f760830db735d35f3316"
os = "macos"

    [[GAP_pkg_float.download]]
    sha256 = "89e57fc97e433031896e492186255d906388d6a6bf5bb72ea1ca8502b82b48c1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.500+0/GAP_pkg_float.v100.0.500.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_float]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "68279eb63e29235d5cd059a4363e32d9138124ef"
libc = "glibc"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "9d3314f04794d6d66c6917b803cfbb0e33f7208e4044d938fa17aaa5c400dcc7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.500+0/GAP_pkg_float.v100.0.500.x86_64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_float]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "058a8ae927265657047e0aa6f746d95854cfb6f8"
libc = "glibc"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "b66b32d5dfcb6bad84346a5f057a39f5b4515e8e6f2057f3c6b1a420becaecd2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.500+0/GAP_pkg_float.v100.0.500.x86_64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_float]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6b6b66989439aa8ba628b8fbaf6d05b83dad2187"
libc = "musl"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "9895a8771667c5e921cc12c4fcca64903ec65b9867f142c922c732e11336b821"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.500+0/GAP_pkg_float.v100.0.500.x86_64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_float]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e93c94a221183772eab805a85b21be955f52d3d"
libc = "musl"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "63be764c105d356bc682465c8e9a370a65c287a82846588c72d61a1707dff23b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.500+0/GAP_pkg_float.v100.0.500.x86_64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_float]]
arch = "x86_64"
git-tree-sha1 = "73f615fd76984e998e49de6d9d6c82a663fd53c7"
os = "freebsd"

    [[GAP_pkg_float.download]]
    sha256 = "40487909181968f019eab45e0f71f8633b5ccf00f4892c5d972b74ef24aba71c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.500+0/GAP_pkg_float.v100.0.500.x86_64-unknown-freebsd.tar.gz"
