[[GAP_pkg_float]]
arch = "aarch64"
git-tree-sha1 = "3664283d2935b271b7c5f687c9a67ae11f2cc06d"
os = "macos"

    [[GAP_pkg_float.download]]
    sha256 = "df9cf96e85b65d8161adf2df174da6854320a9cbb30d58cca5efd5aee9b6560a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.301+0/GAP_pkg_float.v100.0.301.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_float]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c7cfb86f58bdfa1be8699bda6f2322db057896b7"
libc = "glibc"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "923ce0688879bc73c3b43f127249322684f23dd68f65dc6835a429f7e18af08e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.301+0/GAP_pkg_float.v100.0.301.aarch64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_float]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8dc0c12b505ec940dd5734c6471a3f10131f1d98"
libc = "glibc"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "614f7fb656b9c1da02604702c3518943c666794c14d4a8395fa4834ff3306899"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.301+0/GAP_pkg_float.v100.0.301.aarch64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_float]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "728d33fdfbcc66bb339d450f0bbb597af3c64ac7"
libc = "musl"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "ba6834ffacae772956dfae4c67cc942e2c6ae0404ebf6fccbee7cf9043b55bba"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.301+0/GAP_pkg_float.v100.0.301.aarch64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_float]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "de40cf3b42b1b5de143e432aa0f549ba17cae37a"
libc = "musl"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "4f11ad41f530257362a1cf98b54137844a3a295ff8434fb2a706f67acd0ec328"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.301+0/GAP_pkg_float.v100.0.301.aarch64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_float]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2da3dda56fddf7094932a95a94f4e869611f3206"
libc = "glibc"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "d3b4fd4278ef85bddefcfa31449a9245fc4512e9d7305ad44be1b0c3b2fdaa56"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.301+0/GAP_pkg_float.v100.0.301.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_float]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "abc7a126d9a32b8a2a4a73857ccc4b6a948c0993"
libc = "glibc"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "022e499e97542245ff40d99a052d4c6b5974640799d144e4734f2673da95170c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.301+0/GAP_pkg_float.v100.0.301.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_float]]
arch = "x86_64"
git-tree-sha1 = "6e2c11ff903af71a9ee50bd51b6ec0a41fd7c035"
os = "macos"

    [[GAP_pkg_float.download]]
    sha256 = "4c515ad15a0ecaef99c6230387a0f4af928571f4e797411ea19987bf554a61a6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.301+0/GAP_pkg_float.v100.0.301.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_float]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "338f2598dcf1e9532de08c9bd1d19815cf107573"
libc = "glibc"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "fea5b339ff64d4c970a80ba3faed14aabab2db191c5f7657ff8975ad2294c4cb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.301+0/GAP_pkg_float.v100.0.301.x86_64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_float]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f60520e7449cc771fc2b3a0fb5fe2b3aa773975"
libc = "glibc"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "7bd983d972ddcf7e20ba1857aaf74ecc2e6ef00a81fdc1b4c56b16bca3695ed9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.301+0/GAP_pkg_float.v100.0.301.x86_64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_float]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd6e0d4c5490351a7adb20f818f46b1063224ded"
libc = "musl"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "55f31786921862573e0bfa23cb62dd8c9ce45011e2fa588e911d58cd020f9c69"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.301+0/GAP_pkg_float.v100.0.301.x86_64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_float]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5c37050077f678b6028caa8d8e660c60865fcd42"
libc = "musl"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "fa83e80aa87b3ae1d91a1ca1876f0b6fd15bc405469a54f81d3245ddbe362570"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.301+0/GAP_pkg_float.v100.0.301.x86_64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_float]]
arch = "x86_64"
git-tree-sha1 = "b50c9a835649eadce9c9fe86040b2bf3f5104d16"
os = "freebsd"

    [[GAP_pkg_float.download]]
    sha256 = "db18ee1e124e93a45db2434b57a1473818abb638baf527d1efdb2cb156fe392e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.301+0/GAP_pkg_float.v100.0.301.x86_64-unknown-freebsd.tar.gz"
