[[GAP_pkg_float]]
arch = "aarch64"
git-tree-sha1 = "f26d66c0cc9b48da40bb68ddaa56233fd5e1c395"
os = "macos"

    [[GAP_pkg_float.download]]
    sha256 = "89f1d25a5750a7dd1eeb7c96f1cac07dc99a43872fd01a6a27c7b619209de8fa"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.302+0/GAP_pkg_float.v100.0.302.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_float]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "02e779b2ff2df3083fbf64f150cdd44c62dc98a4"
libc = "glibc"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "343dbcc4c8937bdf6a66bafb9252de308c48a70325558479579d9951e8a1fccf"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.302+0/GAP_pkg_float.v100.0.302.aarch64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_float]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a084f70aa4d9350d890197e53887efb7918ece5"
libc = "glibc"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "9e16204273560ad48419fbb23b65be3804346a1981201ef45f3b98b90a427ec6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.302+0/GAP_pkg_float.v100.0.302.aarch64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_float]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5973918469eba3bd600439dff1f145740d893c9c"
libc = "musl"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "42fc41e3724a5916eb1a985c829e9ead0966858edaf9e2074141d6da4aafa0c4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.302+0/GAP_pkg_float.v100.0.302.aarch64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_float]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "527842b2b495a14a0c20bfe1e40f9ac5d4e82633"
libc = "musl"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "5f54643357e565fa6b79c7c07407e5518dfd55845e1629f4bbfb75c6a626e12d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.302+0/GAP_pkg_float.v100.0.302.aarch64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_float]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c81c8378d0694bb6f63ecda812aa44585f4b69a8"
libc = "glibc"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "36b83a75fed7e4b9357a4d9cf8fb2c3e0d2ac1a34668625316067c1dcdf64450"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.302+0/GAP_pkg_float.v100.0.302.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_float]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2aca4a867606b3e42cf869a139bff7b839df61e3"
libc = "glibc"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "849812277b83a249ff412164383ed4c413bde44662c942453dd7bf2f0b9ba787"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.302+0/GAP_pkg_float.v100.0.302.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_float]]
arch = "x86_64"
git-tree-sha1 = "8374bc922f2a9208e64eb74c2c56506964917790"
os = "macos"

    [[GAP_pkg_float.download]]
    sha256 = "0fff30ee16362af6b586e4b34c5b589ae4267face9a29959bf9e360578be1246"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.302+0/GAP_pkg_float.v100.0.302.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_float]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef86d671c9c0af784fba75d487e36c8844f68e81"
libc = "glibc"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "f9b422854e20ad8396aa3314f802d2f691b65bd040951bb66a942fcc16e93cb7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.302+0/GAP_pkg_float.v100.0.302.x86_64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_float]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78237bb2fbbaddb7fee3e246fad7bb079578e22d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "dfe4e0049276d5948953263ab839dd7b59a20a61929571b3a2fbd7253567116a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.302+0/GAP_pkg_float.v100.0.302.x86_64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_float]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b86de1d43a05e01e36697cb1797933b8f921e158"
libc = "musl"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "f3429482b1fd42c99a1fd9d5fa264409ac19ed796689ed9305cc0478e345b668"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.302+0/GAP_pkg_float.v100.0.302.x86_64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_float]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2c28d391ecddc6676072c020b6768a3b4dfdd979"
libc = "musl"
os = "linux"

    [[GAP_pkg_float.download]]
    sha256 = "a54dc80f0b12b0baee355e576c858db0e3bbec9eff2a95bdefbf44e869366711"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.302+0/GAP_pkg_float.v100.0.302.x86_64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_float]]
arch = "x86_64"
git-tree-sha1 = "6f250a95949dd3afdceba458a6ec2f4c4f6731e1"
os = "freebsd"

    [[GAP_pkg_float.download]]
    sha256 = "68a45e317732a6d2fb6014f49d02f1ad9bbfbd3778c2a50bc08a9ca1de37f8a7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_float_jll.jl/releases/download/GAP_pkg_float-v100.0.302+0/GAP_pkg_float.v100.0.302.x86_64-unknown-freebsd.tar.gz"
